# Generated by Django 2.2.10 on 2020-02-19 14:43


from django.db import models, migrations, transaction


def replace_nonestring_with_null(apps, schema_editor):
    with transaction.atomic():
        UpdateRecord = apps.get_model('rpm', 'UpdateRecord')
        for rec in UpdateRecord.objects.all().only('updated_date'):
            if rec.updated_date in ('None', ''):
                rec.updated_date = None
                rec.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0029_rpmpublication_sqlite_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterecord',
            name='updated_date',
            field=models.TextField(null=True),
        ),
        # The string "None" was stored in the database in place of "" or null
        migrations.RunPython(replace_nonestring_with_null),
    ]
