# Generated by Django 3.2.13 on 2022-06-10 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpm', '0043_textfield_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmrepository',
            name='retain_package_versions',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
